# LLM 模型配置
model_name: "gpt-3.5-turbo"

model_temperature: 0.7
model_max_tokens: 4096
model_timeout: 120

model_api_config:
  gpt-3.5-turbo:
    model_list:
      - model_name: "gpt-3.5-turbo"
        model_url: "xxxx" 
        api_key: "xxxx" 
